import type { SeedE2ECase } from './types';

export const outboundCollectionCases: SeedE2ECase[] = [
  { skill_name: 'outbound-collection', input_message: '我这周五之前会还，你把链接发我一下。', expected_keywords: JSON.stringify(['还款', '链接']), assertions: JSON.stringify([{ type: 'skill_loaded', value: 'outbound-collection' }, { type: 'tool_called', value: 'record_call_result' }, { type: 'tool_called', value: 'send_followup_sms' }, { type: 'not_contains', value: '法律后果' }, { type: 'not_contains', value: '起诉' }]), persona_id: 'C001' },
  { skill_name: 'outbound-collection', input_message: '金额太高了，我要人工和你们协商处理。', expected_keywords: JSON.stringify(['人工', '协商']), assertions: JSON.stringify([{ type: 'skill_loaded', value: 'outbound-collection' }, { type: 'tool_called', value: 'record_call_result' }, { type: 'tool_called', value: 'transfer_to_human' }, { type: 'not_contains', value: '信用记录' }]), persona_id: 'C002' },
  { skill_name: 'outbound-collection', input_message: '我现在不方便，明天下午三点你们再打给我。', expected_keywords: JSON.stringify(['回拨', '明天下午']), assertions: JSON.stringify([{ type: 'skill_loaded', value: 'outbound-collection' }, { type: 'tool_called', value: 'create_callback_task' }, { type: 'tool_called', value: 'record_call_result' }]), persona_id: 'C003' },
  { skill_name: 'outbound-collection', input_message: '我其实昨天已经交过费了，你们先去核实一下，不要一直催。', expected_keywords: JSON.stringify(['已经交过费', '核实']), assertions: JSON.stringify([{ type: 'skill_loaded', value: 'outbound-collection' }, { type: 'tool_called', value: 'record_call_result' }, { type: 'not_contains', value: '起诉' }, { type: 'not_contains', value: '法律后果' }]), persona_id: 'C001' },
  { skill_name: 'outbound-collection', input_message: '你打错了，这个号码不是本人。', expected_keywords: JSON.stringify(['不是本人']), assertions: JSON.stringify([{ type: 'skill_loaded', value: 'outbound-collection' }, { type: 'tool_called', value: 'record_call_result' }, { type: 'tool_not_called', value: 'send_followup_sms' }]), persona_id: 'C003' },
  // SOP 顺序验证：承诺还款场景，record_call_result 必须在 send_followup_sms 之前
  { skill_name: 'outbound-collection', input_message: '好吧，我下周一还，发个还款链接给我。', expected_keywords: JSON.stringify(['还款', '链接']), assertions: JSON.stringify([{ type: 'skill_loaded', value: 'outbound-collection' }, { type: 'tool_called', value: 'record_call_result' }, { type: 'tool_called', value: 'send_followup_sms' }, { type: 'tool_called_before', value: 'record_call_result,send_followup_sms' }]), persona_id: 'C001' },
];
